
<?php
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?><?php

try{
					
$collection = $block->getFavorites();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance ();

$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');


$_helper = $this->helper('Magento\Catalog\Helper\Output');
/* @var $_uhHelper UncleHarrys\Catalog\Helper\Data */
$_uhHelper = $this->helper('UncleHarrys\Catalog\Helper\Data');
$empty = true;
?>
    <?php echo $listBlock->getToolbarHtml() ?>
    <?php echo $listBlock->getAdditionalHtml() ?>
    <?php $modecheck = $objectManager->create('Magento\Catalog\Block\Product\ProductList\Toolbar')->getCurrentMode();
    ?>
    <?php
    if ($modecheck == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>




    <div class="products wrapper <?php /* @escapeNotVerified */  ?> products-<?php /* @escapeNotVerified */  ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($collection as $_product): ?>
                <?php
//                var_dump($_product->getProductId());
//                die();
                $empty  = false;
                $_product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getProductId());
//                var_dump($loadedproduct);
//                die();
                echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $listBlock->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                        <?php $isNew = $_uhHelper->isNewProductByDate($_product->getNewsFromDate(), $_product->getNewsToDate()); ?>
                        
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php echo $_product->getName(); ?>
                            </a>
                        </strong>
                        <?php echo $listBlock->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $listBlock->getProductPrice($_product) ?>
                        <?php echo $listBlock->getProductDetailsHtml($_product); ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if (true): ?>
                                        <?php $postParams = $listBlock->getAddToCartPostParams($_product); ?>

                                        <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey')?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="product-item-actions">
                                    <a href="<?php echo $block->getUrl('favorite/index/remove', array('id'=>$_product->getId())); ?>">
                                        <span>Remove Item</span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($collection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
    
  
            </ol>
    </div>
<?php echo $block->getToolbarHtml() ?>
<?php if (!$listBlock->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
<?php endif; ?>


<?php  
if( $empty){ ?>
   <div class="message info empty"><span>You have no items in your favorite list.</span></div>
<?php }
?>








<?php }catch (Exception $e){
    echo $e;
}?>
